### ISSUE TITLE
gl status and gl branch unicode errors

### ISSUE THREAD

**Issue by sandgraham** [sdg-mit/gitless#52] opened 2016-10-02 18:32 UTC
Hi, I'm using the **gl-v0.8.3-darwin-x86_64** bin from the main website. Using **gl status** and **gl branch** results in the following error:

> Traceback (most recent call last):
> File "<string>", line 14, in <module>
> File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.gl", line 80, in main
>  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.pprint", line 80, in err
>  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.pprint", line 40, in puts
>  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/clint.textui.colored", line 52, in func_help
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u2718' in position 0: ordinal not in range(128)

Perhaps I missed something in the installation? Just moved the downloaded bin to my /usr/local/bin.

**Comment by spderosso** [comment] 2016-10-03 04:05
It looks like it is trying but failing to output ✘. My guess is that it happens on `gl status` and `gl branch` because you are not in a Git(less) repo and is thus trying to print the message:
```
✘ You are not in a Gitless's repository
  ➜ do gl init to turn this directory into an empty repository
  ➜ do gl init remote_repo to clone an existing repository
```
But I don't get the same error message. Maybe it's because your Terminal is not using Unicode?

Try the following:
- click on the "Terminal" menu then "Preferences"
- under the "Profiles" tab select your default profile
- click on the "Advanced" tab and  under "International" select for "Text Encoding" the option "Unicode (UTF-8)"

Let me know if that works

**Comment by sandgraham** [comment] 2016-10-03 18:19
Ah I should have mentioned that I am using iTerm (v3.0.10) and that I was testing the commands in a few local repositories started a while back using vanilla git.

For iTerm, looking under Preferences > Profile > Default > Terminal, the Character Encoding is already "Unicode (UTF-8)".

The funny thing is I tried the commands on Terminal in the same repositories and they actually work fine. They don't complain about not being in a Gitless repository. No ✘ even shows up.

If there is any other info I can provide let me know. Maybe I will try building from source later today to see if the same issues occur in iTerm.

**Comment by spderosso** [comment] 2016-10-03 20:00
I downloaded iTerm v3.0.10 and `gl` is working fine for me there. When you try the commands on Terminal what do you see? Do you notice anything unusual in the output?  What do you get if you do `git branch` and `git status` on iTerm?

**Comment by sandgraham** [comment] 2016-10-04 17:53
So testing between Terminal and iTerm. It seems to just be an iTerm issue.

On a non git/gitless directory.

gl status on Terminal:

 ✘ You are not in a Gitless's repository
   ➜ do gl init to turn this directory into an empty repository
   ➜ do gl init remote_repo to clone an existing repository

gl status on iTerm:

Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.gl", line 75, in main
  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.pprint", line 80, in err
  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.pprint", line 40, in puts
  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/clint.textui.colored", line 52, in func_help
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2718' in position 0: ordinal not in range(128)

gl status after initializing with gl init on Terminal:

On branch master, repo-directory //

Tracked files with modifications:
  ➜ these will be automatically considered for commit
  ➜ use gl untrack f if you don't want to track changes to file f
  ➜ if file f was committed before, use gl checkout f to discard local changes

    There are no tracked files with modifications to list


Untracked files:
  ➜ these won't be considered for commit
  ➜ use gl track f if you want to track changes to file f

    index.html

gl status on iTerm:

On branch master, repo-directory //

Tracked files with modifications:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.gl", line 80, in main
  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.pprint", line 80, in err
  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.pprint", line 40, in puts
  File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/clint.textui.colored", line 52, in func_help
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2718' in position 0: ordinal not in range(128)

After digging into the differences a bit more I noticed in gitless/pprint.py on line 32,
`ENCODING = getpreferredencoding() or 'utf-8'`

On Terminal running this yields:

>>> getpreferredencoding()
'UTF-8'

On iTerm it yields:

>>> getpreferredencoding()
'US-ASCII'

I haven't figured out how to alter this for iTerm, as Terminal seems to use the appropriate encoding. I've tried `export PYTHONIOENCODING=utf-8` in my bash profile and setting `sys.setdefaultencoding('utf-8')` in site sitecustomize.py but iTerm seems to bypass this.

**Comment by scottsideleau** [comment] 2016-10-04 21:16
I'm using Gitless with iTerm2 3.0.10 and Homebrew's Python 3.5.2 and Homebrew's Git 2.10.0 without issue.

**Comment by sandgraham** [comment] 2016-10-07 18:10
Ah, I'm on iTerm2 3.0.10, pyenv python 2.7.10, and git 2.8.1 that I believe was installed with xcode dev tools.

Note I've been using gitless fine on Terminal. Can't figure out where my iTerm is setting the preferred encoding to US-ASCII.

**Comment by spderosso** [comment] 2016-11-23 17:10
I am closing this issue since it seems like the problem is not related to Gitless, thanks!

**Closed by spderosso** 2016-11-23 17:10 UTC
