### ISSUE TITLE
gl init not working

### ISSUE THREAD

**Issue by dteiml** [sdg-mit/gitless#186] opened 2018-09-30 06:56 UTC
I have just installed gitless from homewbrew (macOS latest version).

When I run `gl -h` in an empty repository, I get the corresponding output. But when I run `gl init`, I get `fatal: Not a git repository (or any of the parent directories): .git`.

Am I doing something wrong or is this a bug?

Thank you!

**Comment by spderosso** [comment] 2018-09-30 15:07
Thank you for reporting this. This problem is tracked in #179. The fix introduced in #180 should fix it. I will cut a new release with the fix soon.

**Comment by spderosso** [comment] 2018-09-30 15:08
Duplicate of #183

**Closed by spderosso** 2018-09-30 15:08 UTC
Labels: bug

**Comment by dteiml** [comment] 2019-05-24 08:26
I decided to give Gitless another shot, installed it through Homebrew, created a new folder. I'm getting exactly the same result as before. Should I download binary instead?
Thanks

**Comment by spderosso** [comment] 2019-05-25 00:30
I pushed a new release which fixes the bug you are running into. I haven't updated the homebrew formula yet though but in the meantime you can install it from source or use the most recent binary release for macOS.
