### ISSUE TITLE
Detect filesystem changes

### ISSUE THREAD

**Issue by megadr01d** [sdg-mit/gitless#93] opened 2016-11-11 01:09 UTC
```
$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   test3c.txt
	new file:   test5.txt
	new file:   test6.txt
```

```
$ gl status
On branch master, repo-directory //

Tracked files with modifications:
  ➜ these will be automatically considered for commit
  ➜ use gl untrack f if you don't want to track changes to file f
  ➜ if file f was committed before, use gl checkout f to discard local changes

    test3c.txt (new file)
    test5.txt (new file)
    test6.txt (new file)


Untracked files:
  ➜ these won't be considered for commit
  ➜ use gl track f if you want to track changes to file f

    There are no untracked files to list
```

Go to my file manager, delete `test5.txt` and rename `test6.txt` to `test7.txt`.

```
$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   test3c.txt
	new file:   test5.txt
	new file:   test6.txt

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    test5.txt
	deleted:    test6.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test7.txt
```

```
$ gl status
On branch master, repo-directory //
✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:
  
  0.8.4
  
  Traceback (most recent call last):
    File "/usr/local/Cellar/gitless/0.8.4/libexec/lib/python2.7/site-packages/gitless/cli/gl.py", line 73, in main
      return SUCCESS if args.func(args, repo) else ERRORS_FOUND
    File "/usr/local/Cellar/gitless/0.8.4/libexec/lib/python2.7/site-packages/gitless/cli/gl_status.py", line 45, in main
      for f in curr_b.status():
    File "/usr/local/Cellar/gitless/0.8.4/libexec/lib/python2.7/site-packages/gitless/core.py", line 753, in status
      yield self.FileStatus(fp, *self._st_map[git_s])
  KeyError: 513
```

**Comment by langdon-holly** [comment] 2016-11-26 00:46
I also had this problem.
I fused a branch to master, deleted the branch, tried to publish to origin/master but it said "✘ There are changes you need to fuse/merge", so I fused from origin/master, then removed some files (which I had just marked as resolved), then:
```
$ gl status
On branch master, repo-directory //

You are in the middle of a fuse; all conflicts must be resolved before commiting
  ➜ use gl fuse --abort to go back to the state before the fuse
  ➜ use gl resolve f to mark file f as resolved
  ➜ once you solved all conflicts do gl commit to continue

✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:
  
  0.8.4
  
  Traceback (most recent call last):
    File "gitless/cli/gl.py", line 73, in main
    File "gitless/cli/gl_status.py", line 45, in main
    File "gitless/core.py", line 753, in status
  KeyError: 513
```

**Comment by embs** [comment] 2017-12-02 23:31
@spderosso I've also faced the `KeyError: 513` error and it seems to be legitimated / assured by the following test case:

https://github.com/sdg-mit/gitless/blob/bd6761c8c7af85237e2c00f9a3ceda8b373744ec/gitless/tests/test_core.py#L483-L490

Does it mean that users aren't supposed to rm / rename tracked files? Or is this test some temporary condition (meant to be modified in the future)? I didn't understand it.

Thanks!

**Comment by spderosso** [comment] 2017-12-04 23:58
Thanks @megadr01d @langdon-holly @embs. This is a bug, the test case is wrong. The expected behavior if you remove a tracked file is for the file to be removed.

**Closed** 2018-07-26 13:51 UTC
Labels: bug
