### ISSUE TITLE
gl status on OS X fails with installed gl-v0.8-darwin-x86_64.tar

### ISSUE THREAD

**Issue by stefanspringer1** [sdg-mit/gitless#41] opened 2015-08-13 14:59 UTC
$ gl status
On branch master, repo-directory //gltest
✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:

  0.8

  Traceback (most recent call last):
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.gl", line 69, in main
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.cli.gl_status", line 44, in main
    File "/Users/santiago/Documents/code/gitless/build/gl/out00-PYZ.pyz/gitless.core", line 561, in status
  OSError: Failed to open directory '/Users/stefan/Library/Saved Application State/com.bitrock.appinstaller.savedState/': Permission denied

**Comment by spderosso** [comment] 2015-08-13 16:52
Thanks for reporting this.

In the particular line where it crashes ([561 of core.py](https://github.com/sdg-mit/gitless/blob/56664fa596bb3ecc1c1f1e3ffa7a5ecf62825f14/gitless/core.py#L561)) the app is trying to get the status of all files in the repo. I assume your repo doesn't include the `/Users/.../Saved Application State/com.bitrock.appinstaller.savedState` directory, right?

If you can answer the following questions it might help me figure out what's going on:

- The package you installed is the one available from http://gitless.com, right?
- Is it just `gl status` or do all of the other commands fail as well (with the same error)?
- Does it happen consistently every time you do `gl status` or only occasionally?
- If you do `git status` does it work fine?

**Comment by stefanspringer1** [comment] 2015-08-13 17:00
> Am 13.08.2015 um 18:52 schrieb Santiago Perez De Rosso <notifications@github.com>:
> 
> Thanks for reporting this.
> 
> In the particular line where it crashes (561 of core.py <https://github.com/sdg-mit/gitless/blob/56664fa596bb3ecc1c1f1e3ffa7a5ecf62825f14/gitless/core.py#L561>) the app is trying to get the status of all files in the repo. I assume your repo doesn't include the /Users/.../Saved Application State/com.bitrock.appinstaller.savedState directory, right?
> 
> If you can answer the following questions it might help me figure out what's going on:
> 
> The package you installed is the one available from http://gitless.com <http://gitless.com/>, right?

yes
> Is it just gl status or do all of the other commands fail as well (with the same error)?

before tat, „gl init“ was ok
now tried „gl track hallo.txt“ -> ok, no error
> Does it happen consistently every time you do gl status or only occasionally?
consistently
> If you do git status does it work fine?

yes
> —
> Reply to this email directly or view it on GitHub <https://github.com/sdg-mit/gitless/issues/41#issuecomment-130758433>.
> 
Q: what about that folder com.bitrock.appinstaller.savedState? the download was only a tar, no installer

**Comment by spderosso** [comment] 2015-08-13 17:22
On Thu, Aug 13, 2015 at 1:00 PM stefanspringer1 <notifications@github.com>
wrote:

>
> > Am 13.08.2015 um 18:52 schrieb Santiago Perez De Rosso <
> notifications@github.com>:
> >
> > Thanks for reporting this.
> >
> > In the particular line where it crashes (561 of core.py <
> https://github.com/sdg-mit/gitless/blob/56664fa596bb3ecc1c1f1e3ffa7a5ecf62825f14/gitless/core.py#L561>)
> the app is trying to get the status of all files in the repo. I assume your
> repo doesn't include the /Users/.../Saved Application
> State/com.bitrock.appinstaller.savedState directory, right?
> >
> > If you can answer the following questions it might help me figure out
> what's going on:
> >
> > The package you installed is the one available from http://gitless.com <
> http://gitless.com/>, right?
>
> yes
> > Is it just gl status or do all of the other commands fail as well (with
> the same error)?
>
> before tat, „gl init“ was ok
> now tried „gl track hallo.txt“ -> ok, no error
> > Does it happen consistently every time you do gl status or only
> occasionally?
> consistently
> > If you do git status does it work fine?
>
> yes
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/sdg-mit/gitless/issues/41#issuecomment-130758433>.
> >
> Q: what about that folder com.bitrock.appinstaller.savedState? the
> download was only a tar, no installer


Mac OS saves the state of running applications under the `Saved Application
State` folder so that they can be resumed later when you relaunch the app
or after some reboot.

The `com.bitrock.appinstaller.savedState` folder could have been created by
any app that used bitrock's install builder to bundle their app (for
example, I think cmake does). Gitless uses pyinstaller to create the binary
(and we have no installer) so it shouldn't have been created by Gitless.

But I do have that folder on my Library path, so what I am trying to figure
out now is whether when I create the gl binary this folder gets (for some
reason) included in the binary. If you do `ls -al
/Users/stefan/Library/Saved Application
State/com.bitrock.appinstaller.savedState/` what do you see?

**Comment by stefanspringer1** [comment] 2015-08-13 17:27
MacBook-Pro:~ stefan$ ls -al /Users/stefan/Library/Saved\ Application\ State/com.bitrock.appinstaller.savedState/
ls: : Permission denied
MacBook-Pro:~ stefan$ sudo ls -al /Users/stefan/Library/Saved\ Application\ State/com.bitrock.appinstaller.savedState/
Password:
total 16
drwx------    4 root    staff   136 17 Dez  2013 .
drwx------@ 105 stefan  staff  3570 11 Aug 15:26 ..
-rw-------    1 root    staff   464 17 Dez  2013 data.data
-rw-------    1 root    staff   200 17 Dez  2013 windows.plist

**Comment by spderosso** [comment] 2015-08-13 18:24
Seems like those file where there from before you installed Gitless (Dec
2013). Chances are that if you change the permissions to the directory and
the files within it so that your current user can read them then it would
work. Maybe you can you try doing that (let me know if it works).

I am still puzzled as to why the execution of
`self.gl_repo.git_repo.status().items()` would even attempt to read that
directory. Maybe the Python interpreter is trying to find something under
`/Users/.../Library`. I am going to try to reproduce the problem locally
and figure out what's going on.

**Comment by spderosso** [comment] 2016-12-07 01:42
I've been unable to reproduce this so I am closing this issue. If you run into this problem again reopen the issue with more info, thanks

**Closed by spderosso** 2016-12-07 01:42 UTC
